AB_CargoServices/Models/CARGO.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AB_CargoServices.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CARGO
    {
        public Nullable<decimal> VOLUME { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> FEE { get; set; }
        [Key]
        public decimal TRACKING_NO { get; set; }
        public System.DateTime SENT_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal STATUS_ID { get; set; }
        public decimal SENDER_ID { get; set; }
    
        public virtual CARGO_STATUS CARGO_STATUS { get; set; }
        public virtual SENDER SENDER { get; set; }
    }
}

AB_CargoServices/Models/CargoSummary.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AB_CargoServices.Models
{
    public class CargoSummary
    {
        public string SenderName { get; set; }
        public string ReceiverName { get; set; }
        public long TrackingNumber { get; set; }
        public double Weight { get; set; }
        public double Volume { get; set; }
        public double Price { get; set; }
        public DateTime Sent { get; set; }
        public string Description { get; set; }
    }
}

AB_CargoServices/Models/CargoViewModel.cs
using Oracle.ManagedDataAccess.Client;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Web;

namespace AB_CargoServices.Models
{
    // Tracking info page model
    public class CargoViewModel
    {
        public float Weight { get; set; }
        public float Volume { get; set; }
        [Display(Name = "Sender's National ID or Drivers Licence")]
        public long SenderID { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        public CargoViewModel(float weight, float volume, long senderid, string description)
        {
            Volume = volume;
            Weight = weight;
            SenderID = senderid;
            Description = description;
        }
    }

    public class Cities
    {
        public string CityName { get; set; }
    }

    public class CargoDbHandler
    {
        // Database connection setup
        private OracleConnection conn;
        public void Connection()
        {
            string constring = ConfigurationManager.ConnectionStrings["AB_CargoDB"].ConnectionString;
            conn = new OracleConnection(constring);
        }

        // retrieve cities list
        public List<Cities> GetCities()
        {
            Connection();
            List<Cities> myCities = new List<Cities>();

            string queryString = "SELECT * FROM GET_CITIES";
            OracleCommand cmd = new OracleCommand(queryString, conn);
            cmd.CommandType = CommandType.Text;

            DataTable dt = new DataTable();
            OracleDataAdapter oda = new OracleDataAdapter(cmd);

            try
            {
                conn.Open();
                oda.Fill(dt);
                conn.Close();

                foreach(DataRow dr in dt.Rows)
                {
                    myCities.Add(new Cities { CityName = dr["CITY_NAME"].ToString()});
                }

                return myCities;
            }
            catch
            {
                return myCities = null;
            }
            finally
            {
                conn.Close();
            }
        }

        //Add new Cargo
        public string AddNewCargo(CargoViewModel cargo)
        {
            Connection();
            OracleCommand cmd = new OracleCommand("ADD_CARGO", conn);
            cmd.CommandType = CommandType.StoredProcedure;

            cmd.Parameters.Add("WEIGHT_", OracleDbType.Decimal).Value = cargo.Weight;
            cmd.Parameters.Add("VOLUME_", OracleDbType.Decimal).Value = cargo.Volume;
            cmd.Parameters.Add("SENDERID_", OracleDbType.Long).Value = cargo.SenderID;
            cmd.Parameters.Add("DESCRIPTION_", OracleDbType.Varchar2).Value = cargo.Description;

            try
            {
                conn.Open();
                cmd.ExecuteNonQuery();
                conn.Close();

                return "success";
            }
            catch(Exception e)
            {
                return e.ToString();
            }
            finally
            {
                conn.Close();
            }
        }
    }
    
    public class CargoDetailsViewModel
    {
        [Display(Name = "First Name")]
        public string S_FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string S_LastName { get; set; }
        [Display(Name = "First Name")]
        public string R_FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string R_LastName { get; set; }
        [Display(Name = "Cargo Status")]
        public string CargoStatus { get; set; }
    }

    public class CargoDetailsDBHandler
    {
        private OracleConnection conn;
        public void Connection()
        {
            string constring = ConfigurationManager.ConnectionStrings["AB_CargoDB"].ConnectionString;
            conn = new OracleConnection(constring);
        }

        // GET : Get cargo tracking details
        public List<CargoDetailsViewModel> GetTrackingInfo(Int64 tracking_number)
        {
            Connection();
            List<CargoDetailsViewModel> trackingInfo = new List<CargoDetailsViewModel>();
            string queryStr = 
                "SELECT S.FIRST_NAME AS SENDER_FN, S.LAST_NAME AS SENDER_LN, R.FIRST_NAME RECEIVER_FN, R.LAST_NAME AS RECEIVER_LN, CS.MESSAGE AS CARGO_STATUS "+
                "FROM SENDER S, RECEIVER R, CARGO C, CARGO_STATUS CS, C.SENT_DATE, C.DESCRIPTION " + 
                "WHERE C.TRACKING_NO = "+tracking_number+" AND C.SENDER_ID = S.S_ID AND R.SENDER_ID = S.S_ID AND C.STATUS_ID = CS.STATUS_ID";

            OracleCommand cmd = new OracleCommand(queryStr, conn);
            cmd.CommandType = CommandType.Text;

            //cmd.Parameters.Add("TRACKINGID_", OracleDbType.Int64).Value = tracking_number;

            OracleDataAdapter oda = new OracleDataAdapter(cmd);
            DataTable dt = new DataTable();

            try
            {
                conn.Open();
                oda.Fill(dt);
                conn.Close();

                if(dt.Rows.Count > 0 )
                {
                    foreach (DataRow dr in dt.Rows)
                    {
                        trackingInfo.Add(
                                new CargoDetailsViewModel
                                {
                                    S_FirstName = dr["SENDER_FN"].ToString(),
                                    S_LastName = dr["SENDER_LN"].ToString(),
                                    R_FirstName = dr["RECEIVER_FN"].ToString(),
                                    R_LastName = dr["RECEIVER_LN"].ToString(),
                                    CargoStatus = dr["CARGO_STATUS"].ToString()
                                }
                            );
                    }

                    return trackingInfo;
                }
                else
                {
                    return trackingInfo = null;
                }
            }
            catch
            {
                return trackingInfo = null;
            }
            finally
            {
                conn.Close();
            }
        }
    }
}

AB_CargoServices/Controllers/CargoController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using AB_CargoServices.Models;

namespace AB_CargoServices.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class CargoController : Controller
    {
        /*
            public ActionResult Index()
            {
                return RedirectToAction("CargoSummary");
            }

            public ActionResult CargoSummary()
            {
                return View();
            }

            public ActionResult CreateCargo()
            {
                CargoDbHandler cdb = new CargoDbHandler();
                // populate cities for the dropdown list
                ViewBag.Cities = cdb.GetCities().OrderBy(c => c.CityName).ToList().Select(cc => new SelectListItem { Value = cc.CityName.ToString(), Text = cc.CityName }).ToList();

                return View();
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult CreateSender(long tc, string fn, string ln, string address, string city, string phone)
            {
                if(ModelState.IsValid)
                {
                    Sender sender = new Sender(fn, ln, address, city, phone, tc);
                    ViewBag.Sender = sender;
                    CustomerDBHandler cdb = new CustomerDBHandler();
                    ViewBag.Message = cdb.CreateSender(sender);

                    //populate cities for the dropdownlist
                    CargoDbHandler cargoCities = new CargoDbHandler();
                    ViewBag.Roles = cargoCities.GetCities();

                    if (ViewBag.Message == "success")
                    {
                        return View("CargoSummary");
                    }
                    else
                    {
                        return View("CreateCargo");
                    }
                }
                return View("CreateCargo");
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult CreateReceiver(string fn, string ln, string address, string city, string phone)
            {
                if (ModelState.IsValid)
                {
                    Receiver receiver = new Receiver(fn, ln, address, city, phone);
                    ViewBag.Receiver = receiver;
                    CustomerDBHandler cdb = new CustomerDBHandler();
                    ViewBag.Message = cdb.CreateReceiver(receiver);

                    if (ViewBag.Message == "success")
                    {
                        return View("CargoSummary");
                    }
                    else
                    {
                        return View("CreateCargo");
                    }
                }

                return View("CreateCargo");
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult CreateCargo(float weight, float volume, long senderId, string description)
            {
                if(ModelState.IsValid)
                {
                    CargoViewModel cargo = new CargoViewModel(weight, volume, senderId, description);
                    ViewBag.Cargo = cargo;
                    CargoDbHandler cdb = new CargoDbHandler();
                    ViewBag.Message = cdb.AddNewCargo(cargo);

                    if (ViewBag.Message == "success")
                    {
                        return View("CargoSummary");
                    }
                    else
                    {
                        return View("CreateCargo");
                    }
                }

                return View();
            }


            public long ProcessTrackingId(string trackingId)
            {
                return Convert.ToInt64(trackingId);
            }
            public ActionResult TrackingInfo()
            {
                return View();
            }
            */
    }
}

AB_CargoServices/Views/Cargo/CargoSummary.cshtml
@{
    //Layout = "~/Views/Shared/_AdminView.cshtml";
    ViewBag.Title = "CargoSummary";
}

<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <h2 class="text-center">Cargo Summary</h2>
        <div>
           <!-- @Html.ActionLink("Create Cargo", "CreateCargo", "Cargo") -->
        </div>
        <div>@ViewBag.Message</div>
        <div class="panel panel-default">
            <div class="panel-heading">Cargo Information</div>
            <div class="panel-body">
                <div class="pull-right">Cargo Tracking No: <strong>99XXXXXXXXXXXX</strong></div>
                <p><strong>SENDER</strong>   : XXXX XXXXX</p>
                <p><strong>RECEIVER</strong> : XXXX XXXXX</p>
                <h4>Cargo Details</h4>
                <div class="col-xs-6">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Quantity</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Weight</td><td>XXXXX</td>
                            </tr>
                            <tr>
                                <td>Volume</td><td>XXXXX</td>
                            </tr>
                            <tr>
                                <td>Price</td><td>XXXXX</td>                               
                            </tr>
                            <tr>
                                <td>Sent</td><td>XXXXX</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-xs-6">
                    <h3>Description</h3>
                    <hr />
                    <div class="well">
                        Lorem ipsum dore senore lacoste primore
                        barisco tele mundo segundo kapare
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AB_CargoServices/Views/Cargo/CreateCargo.cshtml
@using AB_CargoServices.Models
@{
    ViewBag.Title = "CreateCargo";
}

<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <h2 class="text-center">Add New Cargo</h2>
        <br />
        <div class="panel">
            <div class="panel-heading">Sender</div>
            <small class="text-info">@ViewBag.Message</small>
            <div class="panel-body">
                @using (Html.BeginForm("CreateSender", "Cargo", FormMethod.Post, new { @class = "form-inline"}))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary()
                    
                    <div class="form-group">
                        @Html.Label("TC", new { @class = "control-label" })
                        @Html.TextBox("tc", "", new { @class = "form-control" })
                        
                    </div>
                    <div class="form-group">
                        @Html.Label("FirstName", new { @class = "control-label" })
                        @Html.TextBox("fn", "", new { @class = "form-control" })
                       
                    </div>
                    <div class="form-group">
                        @Html.Label("LastName", new { @class = "control-label" })
                        @Html.TextBox("ln", "", new { @class = "form-control" })
                        
                    </div>
                    <div class="form-group">
                        @Html.Label("Address", new { @class = "control-label" })
                        @Html.TextBox("address", "", new { @class = "form-control" })
                       
                    </div>
                    <div class="form-group">
                        @if (ViewBag.Cities != null)
                        {
                            @Html.DropDownList("city", (IEnumerable<SelectListItem>)ViewBag.Cities, "select city...")
                        }
                        else
                        {
                            //@Html.DropDownList("city", new SelectList(Model.Cities, "Ankara"), "select city...")
                            @Html.Label("City", new { @class = "control-label" })
                            @Html.TextBox("city", "", new { @class = "form-control" })
               
                        }
                    </div>
                    <div class="form-group">
                        @Html.Label("Phone", new { @class = "control-label" })
                        @Html.TextBox("phone", "", new { @class = "form-control" })
                      
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

AB_CargoServices/Views/Cargo/GetTrackingInfo.cshtml
@model AB_CargoServices.Models.TrackingDetailsViewModel
@{
    ViewBag.Title = "GetTrackingInfo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-xs-12">
        @using (Html.BeginForm("GetTrackingInfo", "Cargo", FormMethod.Get))
        {
            <div class="input-group">
                @Html.TextBox("TrackingNo", "", new { @class = "form-control", @placeholder = "TrackID" })
                <div class="input-group-btn">
                    <input type="submit" value="Get Info" class="btn btn-success btn-flat" />
                </div>
            </div>
        }
        <hr />

        @if (Model != null)
        {
            <p>@ViewBag.TrackerMsg</p>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>@Html.DisplayName("SenderFName")</th>
                        <th>@Html.DisplayName("SenderLName")</th>
                        <th>@Html.DisplayName("ReceiverFName")</th>
                        <th>@Html.DisplayName("ReceiverLName")</th>
                        <th>@Html.DisplayName("Date Sent")</th>
                        <th>@Html.DisplayName("Status")</th>
                        <th>@Html.DisplayName("Description")</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Model.SF_Name</td>
                        <td>@Model.SL_Name</td>
                        <td>@Model.RF_Name</td>
                        <td>@Model.RL_Name</td>
                        <td>@Model.Sent</td>
                        <td>@Model.CargoStatus</td>
                        <td>@Model.Description</td>
                    </tr>
                </tbody>
            </table>
        }
        else
        {
            <p class="text-red">@ViewBag.TrackerMsg</p>
        }
    </div>
</div>