AB_CargoServices/Controllers/InquiriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AB_CargoServices.Models;

namespace AB_CargoServices.Controllers
{
    public class InquiriesController : Controller
    {
        private AB_CargoEntities db = new AB_CargoEntities();

        // GET: Inquiries
        public ActionResult Index()
        {
            ViewBag.Inquiries = db.USER_MESSAGES.Count();
            return View(db.USER_MESSAGES.ToList());
        }

        // GET: Inquiries/Details/5
        public ActionResult Details(decimal Id)
        {
            if (Id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER_MESSAGES inquiry = db.USER_MESSAGES.Find(Id);
            if (inquiry == null)
            {
                return HttpNotFound();
            }
            return View(inquiry);
        }

        // GET: Inquiries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Inquiries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SENT,NAME,EMAIL,MESSAGE")] USER_MESSAGES Inquiry)
        {
            if (ModelState.IsValid)
            {
                db.USER_MESSAGES.Add(Inquiry);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(Inquiry);
        }

        // GET: Inquiries/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER_MESSAGES inquiry = db.USER_MESSAGES.Find(id);
            if (inquiry == null)
            {
                return HttpNotFound();
            }
            return View(inquiry);
        }

        // POST: Inquiries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NAME,EMAIL,MESSAGE")] USER_MESSAGES inquiry)
        {
            if (ModelState.IsValid)
            {
                db.Entry(inquiry).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(inquiry);
        }

        // GET: Inquiries/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER_MESSAGES inquiry = db.USER_MESSAGES.Find(id);
            if (inquiry == null)
            {
                return HttpNotFound();
            }
            return View(inquiry);
        }

        // POST: Inquiries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal Id)
        {
            USER_MESSAGES Inquiry = db.USER_MESSAGES.Find(Id);
            db.USER_MESSAGES.Remove(Inquiry);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AB_CargoServices/Views/Inquiries/Create.cshtml
@model AB_CargoServices.Models.USER_MESSAGES

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminView.cshtml";
}

<h2>Let's get in touch</h2>

@using (Html.BeginForm("Create", "Inquiries", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Leave us a message</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.SENT, new { @Value = System.DateTime.Now})
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NAME, "Enter your name please!", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MESSAGE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MESSAGE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MESSAGE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AB_CargoServices/Views/Inquiries/Delete.cshtml
@model AB_CargoServices.Models.USER_MESSAGES

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminView.cshtml";
}

<h2>Delete Inquiry</h2>

@if (Model != null)
{
    <h3>Are you sure you want to delete @Model.NAME?</h3>
    <div>
        <h4>User Inquiry</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.NAME)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.NAME)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.EMAIL)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.EMAIL)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MESSAGE)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MESSAGE)
            </dd>

        </dl>

        @using (Html.BeginForm("Delete", "Inquiries", FormMethod.Post, new { id = Model.ID }))
        {
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
}
else
{
    <p>No contact info to delete</p>
}

AB_CargoServices/Views/Inquiries/Details.cshtml
@model AB_CargoServices.Models.USER_MESSAGES

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminView.cshtml";
}

<h2>Details</h2>

<div>
    <h4>USER_MESSAGES</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MESSAGE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MESSAGE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SENT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SENT)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EMAIL }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AB_CargoServices/Views/Inquiries/Edit.cshtml
@model AB_CargoServices.Models.USER_MESSAGES

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminView.cshtml";
}

<h2>Edit Contact Info</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Contact Us</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.ID)
        <div class="form-group">
            @Html.LabelFor(model => model.NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-6">
                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.EMAIL, "*", new { @class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MESSAGE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MESSAGE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MESSAGE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AB_CargoServices/Views/Inquiries/Index.cshtml
@model IEnumerable<AB_CargoServices.Models.USER_MESSAGES>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminView.cshtml";
}

<section class="content-header">
    <h1>
        User Inquiries
        <small>View, Delete User Inquiries here</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">User Inquiries</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">User Messages</h3>
                </div>
                <div class="box-body">
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.NAME)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.EMAIL)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.MESSAGE)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SENT)
                            </th>
                            <th>Action</th>
                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NAME)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EMAIL)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.MESSAGE)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SENT)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-warning btn-flat btn-sm" }) |
                                    @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "btn btn-primary btn-flat btn-sm" }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-danger btn-flat btn-sm" })
                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
</section>